//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS_Datas
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerLogin
    {
        public int CustomerLoginId { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
