//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS_Datas
{
    using System;
    using System.Collections.Generic;
    
    public partial class Point
    {
        public int PointsId { get; set; }
        public Nullable<int> Amount { get; set; }
        public Nullable<int> Points { get; set; }
        public Nullable<bool> Active { get; set; }
    }
}
