//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS_Datas
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TransactionDetail()
        {
            this.CustomerPoints = new HashSet<CustomerPoint>();
        }
    
        public int TransactionId { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public Nullable<int> Total_Amount { get; set; }
        public Nullable<int> PayModeId { get; set; }
        public Nullable<int> CardId { get; set; }
        public Nullable<int> Payable_Amount { get; set; }
        public Nullable<int> Discount { get; set; }
        public Nullable<int> DeskId { get; set; }
        public Nullable<int> AdminId { get; set; }
    
        public virtual Admin Admin { get; set; }
        public virtual Customer Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerPoint> CustomerPoints { get; set; }
        public virtual Desk Desk { get; set; }
        public virtual PayMode PayMode { get; set; }
        public virtual Card1 Card1 { get; set; }
    }
}
