//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS_Datas
{
    using System;
    using System.Collections.Generic;
    
    public partial class Voucher
    {
        public int VoucherId { get; set; }
        public string VoucherName { get; set; }
        public Nullable<System.DateTime> ValidFrom { get; set; }
        public Nullable<System.DateTime> ValidTo { get; set; }
        public Nullable<bool> Activate { get; set; }
        public Nullable<int> PackagesId { get; set; }
        public Nullable<int> DiscountperId { get; set; }
        public string description { get; set; }
        public Nullable<int> persons { get; set; }
    
        public virtual Discountper Discountper { get; set; }
        public virtual Package Package { get; set; }
    }
}
