//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS_Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class CardRecharge
    {
        public int CardRechargeId { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<int> Amount { get; set; }
        public Nullable<System.DateTime> TodayDate { get; set; }
        public Nullable<bool> Status { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
