//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS_Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class Desk
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Desk()
        {
            this.CustomerCards = new HashSet<CustomerCard>();
            this.CustomerVouchers = new HashSet<CustomerVoucher>();
            this.TransactionDetails = new HashSet<TransactionDetail>();
        }
    
        public int DeskId { get; set; }
        public Nullable<int> AdminId { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public Nullable<bool> Active { get; set; }
        public string DeskName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerCard> CustomerCards { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerVoucher> CustomerVouchers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransactionDetail> TransactionDetails { get; set; }
    }
}
